CREATE TABLE IF NOT EXISTS harcosok (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nev VARCHAR(100) NOT NULL,
	letrehozas DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS kepessegek(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nev VARCHAR(100) NOT NULL,
	leiras VARCHAR(100) NOT NULL,
	harcos_id INTEGER NOT NULL,
	FOREIGN KEY (harcos_id) REFERENCES harcosok(id)
);